### ISSUE TITLE
pageSize=1000 not working as expected

### ISSUE THREAD

**Issue by ch728** [mverouden/brapir-v2#1] opened 2021-09-15 23:22 UTC
Setting pageSize to 1000 only returns 10 results, but setting to 20 returns 20. I have also tested with pageSize=1001 on a private breedbase instance and 1001 results are returned, but setting to 1000 returns  only 10.  Seems to be an issue with specifically pageSize=1000 for some reason.

Here a reproducible example:

```{r}
con <- brapi_connect(db="www.cassavabase.org")  
# This only returns 10 studies
dim(brapi_get_studies(con, pageSize=1000))
# This returns 10
dim(brapi_get_studies(con, pageSize=10))
# This returns 20 
dim(brapi_get_studies(con, pageSize=20))

```

**Comment by mverouden** [comment] 2021-09-16 06:17
Dear Chris,

Thanks for your message. I have looked into it and the problem is not in the BrAPI R v2 package. It is an implementation error on cassavabase.org.

The brapi_get_studies(con = con, pageSize = 1000) function in R creates the following callurl: http://www.cassavabase.org/brapi/v2/studies. This is equivalent to http://www.cassavabase.org/brapi/v2/studies?page=1&pageSize=1000, because the default values are page = 1 and pageSize = 1000.

When you hit cassavabase.org with http://www.cassavabase.org/brapi/v2/studies (try it in a browser), you will see that the default  pagination has been specified as:
`"pagination":{"totalPages":535,"totalCount":5348,"currentPage":0,"pageSize":10}`

This totally explains your results. Please contact the team of Lukas about it (solgenomics), for I think this mistake also exists in other databases based on solgenomics.

**Comment by BrapiCoordinatorSelby** [comment] 2021-09-16 16:12
hey @mverouden there seems to be some confusion around this issue, so I wanted to step in and give my opinion.
I will say that you are correct. According to the BrAPI spec, the server default `pageSize` should be 1000. So if a user of BrAPI-R does not provide a `pageSize`, it is reasonable to assume that most servers will reply with 1000 entries. However, it seems unnecessarily risky to me to ignore an explicit user input value just because it should align with the default. Default values should only be used when there is a lack of information given from the user, any user provided data should take priority.

In this case, I believe there are some technical issues with Breedbase trying to default to 1000. I don't know BrAPI-R as well, is there a technical reason that `pageSize=1000` is being explicitly ignored? Again, @mverouden you are correct according to the spec Breedbase is in the wrong here, but I also believe that BrAPI-R will be more robust and user friendly if this issue were fixed on your end. I am open to mediate more discussion on this if needed.

CC'd @ch728 @MFlores2021

PS
I will also note for clarity, the default value for `page` should be 0, not 1. BrAPI pages should zero indexed.

**Comment by mverouden** [comment] 2021-09-16 16:33
@BrapiCoordinatorSelby I made a typo. For all brapi calls the defaults for pagination are pageSize = 1000 and page = 0. Just had a few minutes to reply before my lecture was starting this morning.

With respect to making the calls more robust you have a good point and it will be a small modification in my code to allways specify pageSize and page in the call when needed. I will look into it and modify a.s.a.p.

**Comment by MFlores2021** [comment] 2021-09-16 21:12
Breedbase sets pageSize = 10 as default since some calls  (i.e. studies) performance can be dramatically affected if default is 1000.Also, most of front end tools work with a small pageSize.  Setting pageSize parameter to the desired value would be more suitable for now. 
https://cassavabase.org/brapi/v2/studies/?pageSize=1000 should give you 1000 values. 
Hope this helps.

**Comment by mverouden** [comment] 2021-09-17 07:28
Callurl's are now created with pagination. When `pageSize` and `page` are not supplied the default values will be used (pageSize = 1000 and page = 0).

Using the example from @ch728 :

```
con <- brapi_connect(db="www.cassavabase.org") 
brapi_serverinfo_show(show = TRUE)
brapi_get_studies(con = con, pageSize = 1000))
# Yields url: http://www.cassavabase.org/brapi/v2/studies?page=0&pageSize=1000
brapi_get_studies(con = con, pageSize = 10)
# Yields url: http://www.cassavabase.org/brapi/v2/studies?page=0&pageSize=10
brapi_get_studies(con = con, page = 1, pageSize = 20)
# Yields url: http://www.cassavabase.org/brapi/v2/studies?page=1&pageSize=20
```

**Closed by mverouden** 2021-09-17 07:28 UTC
Labels: improvement, Priority: High
